name: Stats
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:    
    
jobs:
  build:
    env:
      platform: 
      region:
      account:
    runs-on: ubuntu-latest  

    permissions:
      contents: write
      pages: write
      id-token: write

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.6.0
  
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
     
    - name: Run build or tests
      run: pnpm run build  # or pnpm test, depending on your project setup

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: 'github-pages'
        path: build  
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        artifact_name: ''