name: Stats
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
     contents: write
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8.x  # Use the latest stable version
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
     
    - name: Run build or tests
      run: pnpm run build  # or pnpm test, depending on your project setup

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
